Add Social Auth

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -15,7 +15,7 @@ jobs:
       DATABASE_URL: ${{ secrets.DATABASE_URL }}
       EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
       EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
-      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}  # Add this line
+      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
 
     steps:
       - name: Checkout Repository
@@ -52,7 +52,7 @@ jobs:
       DATABASE_URL: ${{ secrets.DATABASE_URL }}
       EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
       EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
-      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}  # Add this line
+      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
 
     steps:
       - name: Set DATABASE_URL for Deployment
@@ -66,14 +66,28 @@ jobs:
       - name: Set DJANGO_SECRET_KEY for Deployment
         run: echo "DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}" >> $GITHUB_ENV
 
-      - name: Deploy to Production
+      - name: Deploy to Render
         run: |
-          # Add your deployment script or commands here
-          # Example: You might want to run migrations and collect static files
-          python manage.py migrate
-          python manage.py collectstatic --noinput
+          curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" -d '{"branch": "main"}' https://api.render.com/v1/deploys
+
+      - name: Wait for Render Deployment
+        run: |
+          RENDER_SERVICE_NAME="fgfbackend"  # Replace with your Render service name
+          RENDER_ENVIRONMENT="production"  # Change to the appropriate environment
+
+          STATUS=""
+          while [ "$STATUS" != "SUCCEEDED" ] && [ "$STATUS" != "FAILED" ]; do
+              STATUS=$(curl -s -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" https://api.render.com/v1/services/$RENDER_SERVICE_NAME/deploys/latest | jq -r .status)
+              echo "Render deployment status: $STATUS"
+              sleep 10
+          done
+
+          if [ "$STATUS" == "SUCCEEDED" ]; then
+              echo "Render deployment successful!"
+          else
+              echo "Render deployment failed!"
+              exit 1
+          fi
 
       - name: Echo Deployment Status
-        run: echo "Deployment to Production Completed"
-
-# Add any additional steps or jobs as needed
+        run: echo "Deployment to Render Completed"
